version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: geographical_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: geographical
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: geographical_app
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgres://user:password@db:5432/geographical
    ports:
      - "5001:5000"
    depends_on:
      - db

volumes:
  db_data:
